### ISSUE TITLE
explain differences to hi8.cr

### ISSUE THREAD

**Issue by alexanderadam** [spoved/vcr.cr#1]
Hi Holden Omans,

thank you for vcr.cr.

Just a small question: would it be possible to explain in the README which aspects of vcr.cr differ in comparison to [hi8.cr](https://github.com/vonKingsley/hi8.cr) (or [eighttrack](https://github.com/russ/eighttrack))?

Or maybe it would even make sense to join forces with @vonKingsley?

Thank you in advance

**Comment by kalinon** [comment]
Yeah thats a good call. eighttrack really only allowed a single request to be recorded at a time, and seemed to never release the http request if you tried to do more than one.

**Comment by kalinon** [comment]
Updated readme
